### ISSUE TITLE
Outdated link to the FlutterFire repo

### ISSUE THREAD

**Issue by StrangeGirlMurph** [benoitletondor/Beer-Me-Up#6]
Hey
I saw that the link to the FlutterFire repo in your `README.md` file is outdated. 
https://github.com/benoitletondor/Beer-Me-Up/edit/master/README.md#L33
Here is the new one https://github.com/FirebaseExtended/flutterfire. 😀

**Comment by benoitletondor** [comment]
Thanks for the report. As you might have seen, this repo isn't really updated for a while, so it's probably not the only thing outdated

**Comment by StrangeGirlMurph** [comment]
Oh yeah summer 2019 didn't notice. ^^
