### ISSUE TITLE
We want.....

### ISSUE THREAD

**Issue by this-kin** [benoitletondor/Beer-Me-Up#7]
Hi Sir, We want mega Pint

**Comment by benoitletondor** [comment]
Hey, I'm not sure what a mega pint is but anyway, that project is not maintained anymore so it won't happen. Sorry about that

**Comment by this-kin** [comment]
Mega Pint is the Bigger Class, i'm a Flutter Developer too if you don't mind me making a contribution

**Comment by benoitletondor** [comment]
I'm sorry but the project is not maintained so a contribution wouldn't be merged. Thanks for your suggestion and help anyway
